"""end

Revision ID: ebc1cf18d24c
Revises: 
Create Date: 2024-05-09 15:18:26.990064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebc1cf18d24c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.Column('name_cat', sa.String(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id_cat')
    )
    op.create_table('Info',
    sa.Column('id_info', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=63), nullable=True),
    sa.Column('phone', sa.String(length=63), nullable=True),
    sa.Column('schedule', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_info')
    )
    op.create_table('User',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name_user', sa.String(length=63), nullable=True),
    sa.Column('mail', sa.String(length=63), nullable=True),
    sa.Column('password', sa.String(length=63), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('Dish',
    sa.Column('id_dish', sa.Integer(), nullable=False),
    sa.Column('name_dish', sa.String(length=63), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('has_pork', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cat'], ['Category.id_cat'], ),
    sa.PrimaryKeyConstraint('id_dish')
    )
    op.create_table('Message',
    sa.Column('id_mess', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id_mess')
    )
    op.create_table('Order',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('date_order', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('OrderLine',
    sa.Column('id_order_line', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id_dish', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dish'], ['Dish.id_dish'], ),
    sa.ForeignKeyConstraint(['id_order'], ['Order.id_order'], ),
    sa.PrimaryKeyConstraint('id_order_line')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderLine')
    op.drop_table('Order')
    op.drop_table('Message')
    op.drop_table('Dish')
    op.drop_table('User')
    op.drop_table('Info')
    op.drop_table('Category')
    # ### end Alembic commands ###
